module.exports = () => ({
  docs: {
    'front-end': {
      name: '前端',
      index: {
        HTML: 'front-end/HTML/index',
        CSS: 'front-end/CSS/index',
        javaScript: 'front-end/javaScript/index',
        node: 'front-end/node/index',
      },
      color: '',
    },
    'back-end': {
      name: '后端',
      index: {
        python: 'back-end/python/index',
      },
      color: '',
    },
    databases: {
      name: '数据库',
      index: {
        mysql: '',
      },
      color: '',
    },
    operations: {
      name: '运维',
      index: {
        docker: 'operations/docker/index',
      },
      color: '',
    },
    tool: {
      name: '工具',
      index: {
        git: '',
      },
      color: '',
    },
  },
  HTML: {
    categoryOrder: {
      element: 98,
      SVGElement: 99,
      MathMLElement: 100,
    },
    // https://www.w3.org/TR/2017/REC-html52-20171214/semantics.html 4.0-4.12
    typeOrder: {
      docment: 1,
      semantics: 2,
      'document-metadata': 3,
      sections: 4,
      'grouping-content': 5,
      'textlevel-semantics': 6,
      'sec-forms': 7,
      'tabular-data': 8,
      'semantics-embedded-content': 9,
      'semantics-scripting': 10,
      'interactive-elements': 11,
      edits: 12,
      obsolete: 13,
    },
  },
  CSS: {
    categoryOrder: {
      function: 97,
      'At-rules': 98,
      javascript: 99,
      property: 100,
    },
    typeOrder: {
      display: 1,
      sizing: 2,
      box: 3,
      backgrounds: 4,
      fonts: 5,
      color: 6,
      text: 7,
      'text-decor': 8,
      break: 9,
      inline: 10,
      CSS22: 11,
      flexbox: 12,
      grid: 13,
      position: 14,
      align: 15,
      casacde: 16,
      compositing: 17,
      content: 18,
      'device-adapt': 19,
      'fill-stroke': 20,
      'filter-effects': 21,
      images: 22,
      lists: 23,
      logical: 24,
      multicol: 25,
      overflow: 26,
      page: 27,
      'page-floats': 28,
      'round-display': 29,
      'scroll-snap': 30,
      shapes: 31,
      speech: 32,
      tables: 33,
      animations: 34,
      transforms: 35,
      transitions: 36,
      ui: 37,
      variables: 38,
      'will-change': 39,
      'writing-modes': 40,
      masking: 41,
    },
  },
  javaScript: {
    categoryOrder: {
      BOM: 98,
      DOM: 99,
      ECMAScript: 100,
    },
    typeOrder: {
      attribute: 1,
      document: 2,
      element: 3,
      event: 4,
    },
  },
  node: {
    categoryOrder: {},
    typeOrder: {},
  },
  python: {
    categoryOrder: {},
    typeOrder: {},
  },
  docker: {
    categoryOrder: {},
    typeOrder: {},
  },
  git: {
    categoryOrder: {},
    typeOrder: {},
  },
});
